<?php

return [
    Symfony\Bundle\FrameworkBundle\FrameworkBundle::class => ['all' => true],
    Dexodus\TextCaseBundle\TextCaseBundle::class => ['all' => true],
    Dexodus\EntityFormBundle\EntityFormBundle::class => ['all' => true],
    Symfony\Bundle\TwigBundle\TwigBundle::class => ['all' => true],
    Symfony\Bundle\SecurityBundle\SecurityBundle::class => ['all' => true],
    Doctrine\Bundle\DoctrineBundle\DoctrineBundle::class => ['all' => true],
    Doctrine\Bundle\MigrationsBundle\DoctrineMigrationsBundle::class => ['all' => true],
    Nelmio\CorsBundle\NelmioCorsBundle::class => ['all' => true],
    ApiPlatform\Symfony\Bundle\ApiPlatformBundle::class => ['all' => true],
    Dexodus\EntityTableBundle\EntityTableBundle::class => ['all' => true],
    Dexodus\AdminConstructorBundle\AdminConstructorBundle::class => ['all' => true],
    Dexodus\EntityExportBundle\EntityExportBundle::class => ['all' => true],
    Lexik\Bundle\JWTAuthenticationBundle\LexikJWTAuthenticationBundle::class => ['all' => true],
    Symfony\Bundle\MakerBundle\MakerBundle::class => ['dev' => true],
    Dexodus\TranslationApiBundle\TranslationApiBundle::class => ['all' => true],
    Symfony\Bundle\WebProfilerBundle\WebProfilerBundle::class => ['dev' => true, 'test' => true],
    Dexodus\SearchEngineBundle\SearchEngineBundle::class => ['all' => true],
    Dexodus\TitleBundle\TitleBundle::class => ['all' => true],
    Dexodus\DqlFunctionsBundle\DqlFunctionsBundle::class => ['all' => true],
    Dexodus\UserSessionHistoryBundle\UserSessionHistoryBundle::class => ['all' => true],
    Doctrine\Bundle\FixturesBundle\DoctrineFixturesBundle::class => ['dev' => true, 'test' => true],
    Dexodus\EntityHistoryBundle\EntityHistoryBundle::class => ['all' => true],
    Dexodus\EntityDisableBundle\EntityDisableBundle::class => ['all' => true],
    Dexodus\FreeCurrencyApiBundle\FreeCurrencyApiBundle::class => ['all' => true],
];
