parameters:
    emailSender: '%env(MAILER_SENDER)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        public: true
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Dto/'
            - '../src/Kernel.php'
