stages:
    - validate
    - security
    - build
    - deploy

image: docker:27.3.1

variables:
    IMAGE_TAG: "$CI_COMMIT_SHORT_SHA"
    DOCKER_BUILDKIT: "1"
    DOCKER_TLS_CERTDIR: "/certs"

Validate Helm:
    stage: validate
    image: alpine/helm:3.16.3
    rules:
        - if: '$CI_COMMIT_BRANCH'
    script:
        - helm lint ./chart --strict

Secret scan:
    stage: security
    image:
        name: zricethezav/gitleaks:8.18.4
        entrypoint: [""]
    rules:
        - if: '$CI_COMMIT_BRANCH'
    script:
        - gitleaks dir --redact --no-banner .

Build Backend PHP:
    services:
        - name: docker:27.3.1-dind
          command: ["--tls=true"]
    stage: build
    rules:
        - if: '$CI_COMMIT_BRANCH == "main"'
    script:
        - echo "$REGISTRY_PASSWORD" | docker login "$REGISTRY_URL" --username "$REGISTRY_USER" --password-stdin
        - docker build --pull -f docker/php/prod.Dockerfile -t "$REGISTRY_IMAGE_PREFIX/backend-php-prod:$IMAGE_TAG" --build-arg ENVIRONMENT=prod .
        - docker push "$REGISTRY_IMAGE_PREFIX/backend-php-prod:$IMAGE_TAG"

Build Worker PHP:
    services:
        - name: docker:27.3.1-dind
          command: ["--tls=true"]
    stage: build
    rules:
        - if: '$CI_COMMIT_BRANCH == "main"'
    script:
        - echo "$REGISTRY_PASSWORD" | docker login "$REGISTRY_URL" --username "$REGISTRY_USER" --password-stdin
        - docker build --pull -f docker/php/worker.Dockerfile -t "$REGISTRY_IMAGE_PREFIX/worker-php-prod:$IMAGE_TAG" --build-arg ENVIRONMENT=prod .
        - docker push "$REGISTRY_IMAGE_PREFIX/worker-php-prod:$IMAGE_TAG"

Build Backend Nginx:
    services:
        - name: docker:27.3.1-dind
          command: ["--tls=true"]
    stage: build
    rules:
        - if: '$CI_COMMIT_BRANCH == "main"'
    script:
        - echo "$REGISTRY_PASSWORD" | docker login "$REGISTRY_URL" --username "$REGISTRY_USER" --password-stdin
        - docker build --pull -f docker/nginx/prod.Dockerfile -t "$REGISTRY_IMAGE_PREFIX/backend-nginx:$IMAGE_TAG" .
        - docker push "$REGISTRY_IMAGE_PREFIX/backend-nginx:$IMAGE_TAG"

Build and push Frontend:
    services:
        - name: docker:27.3.1-dind
          command: ["--tls=true"]
    stage: build
    rules:
        - if: '$CI_COMMIT_BRANCH == "main"'
    script:
        - echo "$REGISTRY_PASSWORD" | docker login "$REGISTRY_URL" --username "$REGISTRY_USER" --password-stdin
        - docker build --pull -f docker/frontend/prod.Dockerfile -t "$REGISTRY_IMAGE_PREFIX/frontend-prod:$IMAGE_TAG" --build-arg NEXT_PUBLIC_API_URL="$NEXT_PUBLIC_API_URL_PROD" --build-arg NEXT_PUBLIC_API_URL_FROM_SERVER="$NEXT_PUBLIC_API_URL_FROM_SERVER_PROD" .
        - docker push "$REGISTRY_IMAGE_PREFIX/frontend-prod:$IMAGE_TAG"

Deploy In Production Environment:
    stage: deploy
    image: dtzar/helm-kubectl:3.16.3
    rules:
        - if: '$CI_COMMIT_BRANCH == "main"'
          when: manual
    script:
        - kubectl config use-context dexodus-group/exchange-rates:exchange-rates
        - helm upgrade exchange-rates -n default ./chart/ -f ./chart/prod_values.yaml --set-string image.tag="$IMAGE_TAG" --install --atomic --wait --timeout 10m
