doctrine:
    dbal:
        driver: 'pdo_pgsql'
        server_version: '13.1'
        charset: utf8
        default_table_options:
            charset: utf8
            collate: utf8_unicode_ci
        dbname: '%env(resolve:POSTGRES_DB)%'
        user: '%env(resolve:POSTGRES_USER)%'
        password: '%env(resolve:POSTGRES_PASSWORD)%'
        host: '%env(resolve:POSTGRES_HOST)%'
        port: 5432

    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        filters:
            disabled_filter:
                class: Dexodus\EntityDisableBundle\Doctrine\Filter\DisabledFilter
                enabled: true
        mappings:
            App:
                is_bundle: false
                type: attribute
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
            SmiParser:
                is_bundle: false
                type: attribute
                dir: '%kernel.project_dir%/vendor/dexodus/smi-parser-bundle/src/Entity'
                prefix: 'Dexodus\SmiParserBundle\Entity'
                alias: SmiParser
        dql:
            string_functions:
                JSON_CONTAINS: Dexodus\DqlFunctionsBundle\Dql\JsonContains
                JSON_TO_TEXT: Dexodus\DqlFunctionsBundle\Dql\JsonText
                TO_INT: Dexodus\DqlFunctionsBundle\Dql\CastToInt
                GENDER_FROM_IIN: Dexodus\DqlFunctionsBundle\Dql\GenderFromIin
                YEAR: Dexodus\DqlFunctionsBundle\Dql\Year
                MONTH: Dexodus\DqlFunctionsBundle\Dql\Month
                DAY: Dexodus\DqlFunctionsBundle\Dql\Day
