entity_form:
    mapping:
        -   dir: '%kernel.project_dir%/src/Entity'
            prefix: 'App\Entity'
        -   dir: '%kernel.project_dir%/bundles/smi/web-resource-bundle/src/Entity'
            prefix: 'Dexodus\WebResourceBundle\Entity'
        -   dir: '%kernel.project_dir%/bundles/general/location-bundle/src/Entity'
            prefix: 'Dexodus\LocationBundle\Entity'
        -   dir: '%kernel.project_dir%/bundles/smi/telegram-parser-bundle/src/Entity'
            prefix: 'Dexodus\TelegramParserBundle\Entity'
