typescript_types:
  mapping:
    - dir: '%kernel.project_dir%/src/Entity'
      prefix: 'App\Entity'
    - dir: '%kernel.project_dir%/src/Dto'
      prefix: 'App\Dto'
    - dir: '%kernel.project_dir%/vendor/dexodus/smi-parser-bundle/src/Entity'
      prefix: 'Dexodus\SmiParserBundle\Entity'
    - dir: '%kernel.project_dir%/vendor/dexodus/telegram-parser-bundle/src/Entity'
      prefix: 'Dexodus\TelegramParserBundle\Entity'
