apiVersion: apps/v1
kind: Deployment
metadata:
    name: exchange-rates-{{ .Values.env }}-frontend-deployment
    labels:
        env: {{ .Values.env }}
        type: exchange-rates-{{ .Values.env }}-frontend-deployment
spec:
    selector:
        matchLabels:
            env: {{ .Values.env }}
            type: exchange-rates-{{ .Values.env }}-frontend
    template:
        metadata:
            labels:
                env: {{ .Values.env }}
                type: exchange-rates-{{ .Values.env }}-frontend
        spec:
            dnsPolicy: ClusterFirstWithHostNet
            imagePullSecrets:
                -   name: regcred
            containers:
                -   name: exchange-rates-frontend
                    image: "registry.gitlab.com/dexodus-group/exchange-rates/frontend-{{ .Values.env }}:{{ .Values.image.tag}}"
                    ports:
                        -   containerPort: 3000
