apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: exchange-rates-{{ .Values.env }}-frontend-ingress
spec:
  entryPoints:
    - websecure
  routes:
    - match: 'Host(`{{ .Values.domain.frontend }}`)'
      kind: Rule
      services:
        - name: exchange-rates-{{ .Values.env }}-frontend-service
          port: web
  tls:
    certResolver: myresolver
