services:
    Dexodus\EntityExportBundle\:
        resource: '../..'
        public: true
        autowire: true
        autoconfigure: true
        exclude:
            - '../../Attribute/'
            - '../../Dto/'
            - '../../Exception/'
