-- ISMI core schema for Supabase PostgreSQL.
-- Apply this migration through the Supabase CLI or dashboard SQL editor.
-- Application access is governed by the RLS policies below; service_role is not used by the frontend.

create extension if not exists pgcrypto;

create type public.ismi_role as enum ('ROLE_ADMIN', 'ROLE_SUPERVISOR', 'ROLE_EMPLOYEE', 'ROLE_USER');
create type public.subscription_type as enum ('trial', 'monthly', 'yearly', 'custom');

create table public.profiles (
    id uuid primary key references auth.users(id) on delete cascade,
    email text not null unique,
    first_name text not null default '',
    last_name text not null default '',
    patronymic text not null default '',
    iin text not null default '',
    roles public.ismi_role[] not null default array['ROLE_USER']::public.ismi_role[],
    disabled boolean not null default false,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table public.organizations (
    id bigint generated by default as identity primary key,
    name text not null,
    bin text not null,
    city text,
    supervisor_id uuid references public.profiles(id) on delete set null,
    created_by uuid references public.profiles(id) on delete set null,
    employee_limit integer not null default 10 check (employee_limit > 0),
    project_limit integer not null default 5 check (project_limit > 0),
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    unique (bin)
);

create table public.organization_members (
    organization_id bigint not null references public.organizations(id) on delete cascade,
    user_id uuid not null references public.profiles(id) on delete cascade,
    role public.ismi_role not null check (role in ('ROLE_SUPERVISOR', 'ROLE_EMPLOYEE')),
    created_at timestamptz not null default now(),
    primary key (organization_id, user_id)
);

create table public.projects (
    id bigint generated by default as identity primary key,
    organization_id bigint not null references public.organizations(id) on delete cascade,
    name text not null,
    tags text[] not null default '{}',
    disabled boolean not null default false,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table public.articles (
    id bigint generated by default as identity primary key,
    title text not null,
    content text not null,
    announce text,
    source_url text,
    source_name text,
    published_at timestamptz,
    created_at timestamptz not null default now()
);

create table public.project_articles (
    id bigint generated by default as identity primary key,
    project_id bigint not null references public.projects(id) on delete cascade,
    article_id bigint not null references public.articles(id) on delete cascade,
    favorite boolean not null default false,
    unique (project_id, article_id)
);

create table public.organization_accounts (
    id bigint generated by default as identity primary key,
    organization_id bigint not null references public.organizations(id) on delete cascade,
    parser_name text not null,
    account_name text not null,
    options jsonb not null default '{}',
    created_at timestamptz not null default now()
);

create table public.subscriptions (
    id bigint generated by default as identity primary key,
    organization_id bigint not null references public.organizations(id) on delete cascade,
    type public.subscription_type not null,
    starts_at timestamptz not null,
    ends_at timestamptz not null,
    active boolean not null default false,
    price integer,
    price_for_project_improvements integer,
    disabled boolean not null default false,
    check (ends_at >= starts_at)
);

create index projects_organization_id_idx on public.projects(organization_id);
create index project_articles_project_id_idx on public.project_articles(project_id);
create index project_articles_article_id_idx on public.project_articles(article_id);
create index organization_members_user_id_idx on public.organization_members(user_id);

create or replace function public.is_ismi_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
    select exists (
        select 1
        from public.profiles
        where id = auth.uid()
          and disabled = false
          and 'ROLE_ADMIN' = any(roles)
    );
$$;

create or replace function public.can_access_organization(target_organization_id bigint)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
    select public.is_ismi_admin() or exists (
        select 1
        from public.organization_members
        where organization_id = target_organization_id
          and user_id = auth.uid()
    );
$$;

alter table public.profiles enable row level security;
alter table public.organizations enable row level security;
alter table public.organization_members enable row level security;
alter table public.projects enable row level security;
alter table public.articles enable row level security;
alter table public.project_articles enable row level security;
alter table public.organization_accounts enable row level security;
alter table public.subscriptions enable row level security;

create policy "profile owners and admins can read profiles" on public.profiles for select
using (id = auth.uid() or public.is_ismi_admin());
create policy "profile owners can update their profile" on public.profiles for update
using (id = auth.uid()) with check (id = auth.uid());

create policy "members can read their organizations" on public.organizations for select
using (public.can_access_organization(id));
create policy "admins manage organizations" on public.organizations for all
using (public.is_ismi_admin()) with check (public.is_ismi_admin());

create policy "members can read organization memberships" on public.organization_members for select
using (public.can_access_organization(organization_id));
create policy "admins manage organization memberships" on public.organization_members for all
using (public.is_ismi_admin()) with check (public.is_ismi_admin());

create policy "members manage accessible projects" on public.projects for all
using (public.can_access_organization(organization_id)) with check (public.can_access_organization(organization_id));
create policy "members read project articles" on public.project_articles for select
using (exists (select 1 from public.projects where projects.id = project_id and public.can_access_organization(projects.organization_id)));
create policy "members manage project article flags" on public.project_articles for all
using (exists (select 1 from public.projects where projects.id = project_id and public.can_access_organization(projects.organization_id)))
with check (exists (select 1 from public.projects where projects.id = project_id and public.can_access_organization(projects.organization_id)));
create policy "members read articles for their projects" on public.articles for select
using (exists (select 1 from public.project_articles join public.projects on projects.id = project_articles.project_id where project_articles.article_id = articles.id and public.can_access_organization(projects.organization_id)));
create policy "members manage parser accounts" on public.organization_accounts for all
using (public.can_access_organization(organization_id)) with check (public.can_access_organization(organization_id));
create policy "members read subscriptions" on public.subscriptions for select
using (public.can_access_organization(organization_id));
create policy "admins manage subscriptions" on public.subscriptions for all
using (public.is_ismi_admin()) with check (public.is_ismi_admin());
