{{- if .Values.worker.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: exchange-rates-{{ .Values.env }}-backend-worker
  labels:
    env: {{ .Values.env }}
    app: exchange-rates-{{ .Values.env }}-worker
spec:
  replicas: {{ .Values.worker.replicas }}
  selector:
    matchLabels:
      env: {{ .Values.env }}
      app: exchange-rates-{{ .Values.env }}-worker
  template:
    metadata:
      labels:
        env: {{ .Values.env }}
        app: exchange-rates-{{ .Values.env }}-worker
    spec:
      automountServiceAccountToken: false
      dnsPolicy: ClusterFirst
      imagePullSecrets:
        - name: {{ .Values.imagePullSecret }}
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: worker
          image: "registry.gitlab.com/dexodus-group/exchange-rates/worker-php-{{ .Values.env }}:{{ .Values.image.tag }}"
          imagePullPolicy: IfNotPresent
          command:
            {{- toYaml .Values.worker.command | nindent 12 }}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
          resources:
            {{- toYaml .Values.worker.resources | nindent 12 }}
          {{- if .Values.existingSecret }}
          envFrom:
            - secretRef:
                name: {{ .Values.existingSecret }}
          {{- end }}
      restartPolicy: Always
{{- end }}
