services:
    Dexodus\TitleBundle\:
        resource: '../..'
        public: true
        autowire: true
        autoconfigure: true
        exclude:
            - '../../Attribute/'
            - '../../Exception/'
